### ISSUE TITLE
There are no stupid questions

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-5#14]
<img width="479" alt="Screen Shot 2019-10-11 at 08 59 54" src="https://user-images.githubusercontent.com/28838993/66634709-857c0580-ec05-11e9-800f-f02144f29df7.png">

I'm assuming this was added with a sense of irony as we all know that there is no such thing as a stupid question, but I didn't see the humour at first - It felt like your app was calling me stupid 😢

Please consider the UX of your tone of voice - your user can read things in a very different way than you mean them and people can be very sensitive.

https://medium.com/deliveroo-design/how-to-use-voice-and-tone-in-ux-writing-a66981c78d20

**Comment by Joaoviana** [comment]
That's completely true Michael. What might be 'funny' for us might not be for others! Will change that asap
