### ISSUE TITLE
User gets feedback 🎉

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/project-week-5#18]
The form validation is great, and it's great that the user gets feedback if their form submission isn't valid or if the server is offline. Nice job.

I'm assuming you're still working on this so if you've already considered the following you can ignore me and carry on 

This could be even better if:
- You use a text element on the page to display messages, rather than an alert box
- You translate a bit more for the user (e.g. user won't know what a string is, won't understand status codes)
- Text input remains in the input field when validation fails, so the user doesn't have to start typing all over again

**Comment by marthaklambert** [comment]
This is made clearer with APICalls.js in the error-validation branch commit
